# NUMPY

* Numpy는 Numerical Python의 줄임말로 고성능의 수치 계산 (과학 연산)을 위해 만들어진 Python 확장 패키지이다.
* 숫자 연산을 할 때 리스트 를 사용하는 것보다 Numpy 패키지를 사용하면 더 효율적이고 편리하게 연산을 수행할 수 있다.

<br>
### ndarray

* Numpy에서 가장 강력한 무기로 칭송받는 N 차원의 배열(array) 객체
* n dimensional array 의 줄임말

<br>
### ndarray를 사용하는 이유 

* ndarray는 numpy에서 지원하는 표준형인 벡터/행렬 을 저장한다.
* 많은 numpy 함수가 matrix가 아니라 array를 반환한다.
* 요소 간 연산과 선형대수 연산에 대해선 명확히 구분되어 있다.
* 표준 벡터나 열벡터/행벡터를 표현할 수 있다.

In [3]:
import numpy as np

### ndarray 만들기

* array( ) 함수를 사용하여 ndarray를 만든다.

In [2]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

In [5]:
b=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [6]:
type(b)

numpy.ndarray

In [7]:
b.shape

(3, 5)

In [8]:
b.ndim

2

In [9]:
b.size

15

In [10]:
b[0]

array([0, 1, 2, 3, 4])

In [11]:
b[1]

array([5, 6, 7, 8, 9])

In [12]:
b[2]

array([10, 11, 12, 13, 14])

In [13]:
b[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
b[0,0]

0

In [15]:
b[0,1]

1

In [16]:
b[1,1]

6

In [17]:
b[1,-1]

9

In [18]:
b[-1,-1]

14

### 주의

In [19]:
c=np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

### 특수형태의 array 만들기

In [22]:
d=np.zeros((2,3))
print(d)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [23]:
e=np.ones((1,2))
print(e)

[[ 1.  1.]]


In [24]:
e.shape

(1, 2)

In [25]:
e[0]

array([ 1.,  1.])

In [26]:
e[0,0]

1.0

In [27]:
f=np.ones((2))
print(f)

[ 1.  1.]


In [28]:
f.shape

(2,)

In [29]:
f[0]

1.0

In [30]:
f[0,0]

IndexError: too many indices for array

In [31]:
g=np.full((2,3),7)
print(g)

[[7 7 7]
 [7 7 7]]


In [32]:
h=np.eye(3)
print(h)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [33]:
i=np.random.random((2,3))
print(i)

[[ 0.52307335  0.96884366  0.65174846]
 [ 0.99073677  0.48328254  0.234173  ]]


<br><br>
arange( )는 파이썬의 range( )와 유사한 함수로, 숫자 들의 시퀀스(sequence)를 만들어 array를 반환한다.

In [34]:
j=np.arange(10,30,5)
print(j)
type(j)

[10 15 20 25]


numpy.ndarray

### 슬라이싱

In [35]:
b=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [36]:
print(b.shape)

(3, 5)


In [37]:
b[0, :3]

array([0, 1, 2])

In [38]:
b[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [39]:
b[:2, 1:3]

array([[1, 2],
       [6, 7]])

In [40]:
b[1,2]=77
print(b)

[[ 0  1  2  3  4]
 [ 5  6 77  8  9]
 [10 11 12 13 14]]


In [41]:
b=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [42]:
b[0]

array([0, 1, 2, 3, 4])

In [43]:
b[0,:]

array([0, 1, 2, 3, 4])

In [44]:
b[0][:]

array([0, 1, 2, 3, 4])

In [45]:
b[0,4]

4

In [46]:
b[0][4]

4

In [47]:
b[:,0]

array([ 0,  5, 10])

### 불 배열 인덱싱 (Boolean array indexing )

* 불 배열 인덱싱은 특정 조건을 만족여부를 True, False 로 표시한다.
* 불 배열 인덱싱을 통하여 특정 조건을 만족하는 배열 요소만을 선택할 수 있다.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [ ]:
bool_idx = (a > 2)  

In [ ]:
print(bool_idx)

In [ ]:
print(a[bool_idx])  

In [ ]:
print(a[a > 2]) 

## 배열 연산

In [15]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.array([[6,8],[10,12]])

In [11]:
print(x)

[[1 2]
 [3 4]]


In [12]:
print(y)

[[5 6]
 [7 8]]


In [7]:
print(x + y)

[[ 6  8]
 [10 12]]


In [20]:
z=x+y
z

array([[ 6,  8],
       [10, 12]])

In [ ]:
print(np.add(x, y))

In [ ]:
print(x - y)

In [ ]:
print(np.subtract(x, y))

In [ ]:
print(x * y)

In [ ]:
print(np.multiply(x, y))

In [ ]:
print(x / y)

In [ ]:
print(np.divide(x, y))

In [ ]:
print(np.sqrt(x))

### sum

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
print(np.sum(x))

In [ ]:
print(np.sum(x, axis=0))

In [ ]:
print(np.sum(x, axis=1)) 

### 벡터 내적

In [ ]:
v = np.array([1, 2])
w = np.array([3, 4])

In [ ]:
print(v.dot(w))

In [ ]:
print(np.dot(v, w))

# 이 외에도 많은 함수들이 있으나 생략한다.